name: changelog
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  get-and-write-changelog:
    runs-on: ubuntu-latest
    # if: ${{ github.event.pull_request.merged == true}}
    steps: 
      - uses: actions/checkout@v1
      - run: yarn
      - uses: ./
        with:
          data: ${{ github.event }}